#!/bin/bash

HOST_BACKUPS=./backup
PROJECT_NAME=odoo_project_template

docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo -v $HOST_BACKUPS:/backup postgres:10.10 pg_dump -Uodoo --file /backup/db.pg --format=c db -h db
