#!/bin/bash

HOST_BACKUPS=/Users/tony/odoo_extra/odoo_deploy_test/backup
PROJECT_NAME=tony_odoo-deploy-test

docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo -v $HOST_BACKUPS:/backup postgres:10.10 pg_dump -Uodoo --file /backup/db.pg --format=c db -h db
