#!/bin/bash

HOST_BACKUPS=/Users/tony/odoo_extra/odoo_deploy_test/backup
PROJECT_NAME=tony_odoo-deploy-test
docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo  -e PGUSER=odoo postgres:9.6 createdb -h db -O odoo prod
docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo -e PGUSER=odoo -v $HOST_BACKUPS:/backup postgres:9.6 pg_restore -h db -O -U odoo -j2 -d prod /backup/db.pg
