#!/bin/bash

HOST_BACKUPS=./backup
PROJECT_NAME=odoo_project_template
docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo  -e PGUSER=odoo postgres:10.10 createdb -h db -O odoo prod
docker run --rm --net=${PROJECT_NAME}_default -e PGPASSWORD=odoo -e PGUSER=odoo -v $HOST_BACKUPS:/backup postgres:10.10 pg_restore -h db -O -U odoo -j2 -d prod /backup/db.pg
