services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: postgres:10.10
    ports:
      - 5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "./.db:/var/lib/postgresql/data"
  odoo:
    build: odoo
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - MARABUNTA_MODE=full
    labels:
      docky.access.help: http://${COMPOSE_PROJECT_NAME}.dy
      traefik.enable: true
      traefik.http.routers.odoo.rule: Host(`${COMPOSE_PROJECT_NAME}.dy`)
      traefik.http.routers.odoo.service: odoo
      traefik.http.services.odoo.loadbalancer.server.port: 8069
      traefik.http.routers.odoo.entrypoints: web
      traefik.http.routers.odoolongpolling.rule: Host(`${COMPOSE_PROJECT_NAME}.dy`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.odoolongpolling.service: odoolongpolling
      traefik.http.services.odoolongpolling.loadbalancer.server.port: 8072
      traefik.http.routers.odoolongpolling.entrypoints: web
    links:
      - db
      # - adminer
      # - mailcatcher
      - traefik 
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
volumes:
  py3o_tmp: null
